/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/development',
        'getting-started/docker',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/components',
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        'api/overview',
        'api/authentication',
        'api/pagination',
        'api/error-handling',
        {
          type: 'category',
          label: 'Examples',
          items: [
            'api/examples/javascript',
            'api/examples/python',
            'api/examples/curl',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Interactive API documentation generated from OpenAPI spec.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/overview',
        'deployment/aws',
        'deployment/containerization',
        'deployment/serverless',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [
        'infrastructure/overview',
        'infrastructure/aws-modules',
        'infrastructure/terraform-examples',
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        'testing/overview',
        'testing/unit-tests',
        'testing/integration-tests',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/workflow',
        'contributing/standards',
        'contributing/pull-requests',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/creating-api',
        'tutorials/resource-management',
        'tutorials/reservation-system',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/configuration',
        'reference/environment-variables',
        'reference/cli-commands',
        'reference/troubleshooting',
      ],
    },
  ],
};

module.exports = sidebars;
